import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.scss";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Rayca Assessment",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <Theme
          appearance="dark"
          accentColor="gray"
          grayColor="slate"
          radius="large"
        >
          {children}
        </Theme>
      </body>
    </html>
  );
}
