import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rayca Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme appearance="dark" accentColor="gray" grayColor="slate" radius="large">
          {children}
        </Theme>
      </body>
    </html>
  );
}
